GET http://127.0.0.1:8080/index HTTP/1.1

###
GET http://127.0.0.1:8080/home HTTP/1.1

###
POST http://127.0.0.1:8080/login HTTP/1.1
Content-Type: application/json

{"username": "user", "password": "111"}